name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_FLAGS="-static" ..
          make -j$(nproc)
          mv libcexp.a ..
          mv libcexp.so ..
      
      - name: Upload artifact (static)
        uses: actions/upload-artifact@v4
        with:
          name: cexp-static
          path: libcexp.a
      
      - name: Upload artifact (shared)
        uses: actions/upload-artifact@v4
        with:
          name: cexp-shared
          path: libcexp.so
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download artifact (static)
        uses: actions/download-artifact@v4
        with:
          name: cexp-static

      - name: Download artifact (shared)
        uses: actions/download-artifact@v4
        with:
          name: cexp-shared

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-release
          name: 'Nightly Release'
          body: |
            Automated nightly release for commit ${{ github.sha }}. This release contains all of the newest features.
          files: |
            ./libcexp.a
            ./libcexp.so
